### PR TITLE
Kh dev

### PR DESCRIPTION
**Pull request by kennethshsu**
- Separated workbooks (now blank with solutions)
- Fixed URLs to open workbooks

### CODE REVIEW

**Review by jbogaardt — APPROVED** [review]

**Comment by jbogaardt** [comment]
I've cleared this, but it has a merge conflict. Not sure which docs you want. Can you resolve the conflict @kennethshsu

**Comment by kennethshsu** [comment]
For some reason, my VS conflict resolver isn't working properly... It should be good now.

Also, is it best practice to get rid of a branch after every approved PR? I see that all the old commit history records are still there, and showing up again after a new PR, even after a prior commit had already been approved.

**Comment by kennethshsu** [comment]
> For some reason, my VS conflict resolver isn't working properly... It should be good now.
> 
> Also, is it best practice to get rid of a branch after every approved PR? I see that all the old commit history records are still there, and showing up again after a new PR, even after a prior commit had already been approved.

Ahh, I think I know why now, because even though you approved the PR, it wasn't actually merged, until just now right?

**Comment by kennethshsu** [comment]
There are still some issues with the current version, I should've had committed it yet.

- On the [getting started landing page](https://chainladder-python.readthedocs.io/en/latest/getting_started/index.html) the "cells" are not clickable
- Binder unable to launch the workbook

**Pull request merged**
