### PR TITLE
#510

### PR DESCRIPTION
**Pull request by kennethshsu**
Addressed #510

### CODE REVIEW

**Comment by kennethshsu** [comment]
@jbogaardt can you review this PR?

**Comment by jbogaardt** [comment]
> @jbogaardt can you review this PR?

I thought I did. Did you not see my comments?  Pandas is deprecating "Y" and moving towards "A" for 2.2 and later. Refer to their [release note](https://pandas.pydata.org/docs/whatsnew/v2.2.0.html#deprecate-aliases-m-q-y-etc-in-favour-of-me-qe-ye-etc-for-offsets).  It looks like you're code change says to use the deprecated "Y" value for newer versions of pandas which seems wrong. 

There is also a new conditional which doesn't actually compare against a version number:
```python
"Y" if version.Version(pd.__version__) else "A"
```
Everything is "truthy" in python so this will always return "Y" regardless of the pandas version.

**Review by jbogaardt — APPROVED** [review]

**Comment by kennethshsu** [comment]
I never saw those comments, but thanks for the feedback and approving the PR. :)

I think I'll keep the equal sign the way it is in the PR, since `2.2 and later` means `>= 2.2`.

**Comment by kennethshsu** [comment]
@jbogaardt, can you double-check that `A` is preferred and that `Y` is being deprecated by `pandas`? I just checked the doc you linked and I don't see it.

In fact, I am still getting the warning:
```python
FutureWarning: 'A-DEC' is deprecated and will be removed in a future version, please use 'Y-DEC' instead.
```

**Comment by jbogaardt** [comment]
> @jbogaardt, can you double-check that `A` is preferred and that `Y` is being deprecated by `pandas`? I just checked the doc you linked and I don't see it.
> 
> In fact, I am still getting the warning:
> 
> ```python
> FutureWarning: 'A-DEC' is deprecated and will be removed in a future version, please use 'Y-DEC' instead.
> ```

Thanks @kennethshsu , you're right. My brain is backwards. 'A' is being deprecated in favor of 'Y'.

**Pull request merged**
