### PR TITLE
#514

### PR DESCRIPTION
**Pull request by kennethshsu**
- Addressed #514.
This is done by removing [secondary_rank](https://github.com/casact/chainladder-python/compare/%23514?expand=1#diff-e4811ac35addcd44905fb8e503aeac1de4816ff160955cd40efe4c3a82c0cc7fL520-L531).
@henrydingliu, do you remember why you did this? None of the tests failed, and I couldn't figure out what its supposed to do.
- Added test in #517.

### CODE REVIEW

**Comment by kennethshsu** [comment]
If this PR is approved, I think I will need to go back and remove all the dependent sub functions to not pass in that argument. We will need to modify the tests too. I'm sure Henry has a reason for this, but it's also been a while. I wonder if it was a way to get around some upstream bug.

**Comment by henrydingliu** [comment]
someone had an issue where drop_hilo behaved unpredictably. on a column like this

1.2
1
1
1
1.1
1

if you do ex hilo and volume weighted, it wasn't obvious which 1 would be dropped. secondary rank would allow you to specify if you want to drop maybe the oldest 1 or the 1 with the smallest underlying loss. 

I'm surprise that removing secondary_rank would do anything. it looked to be an optional argument that defaults to blank.

**Comment by kennethshsu** [comment]
I see, that makes a lot of sense now after reading the comments again. But this is not currently captured in any of the tests right? That's why this PR is still passing all tests.

Removing the argument does fix #514 because these [lines](https://github.com/casact/chainladder-python/blob/d21f12523d45441f8b300af2296b00f68b7618fd/chainladder/development/development.py#L139-L142) are causing problems. The primary is `obj.age_to_age` but the secondary is `obj.iloc[...,:-1,:-1]`. However, I believe we can only do this when the triangle is symmetrical (i.e. an isosceles right triangle, with origin and development having the same size?).

I propose that we accept this PR first, we need to write new tests and maybe start a discussion on how to handle all the conflict collision, especially when dealing with very special cases.

**Comment by henrydingliu** [comment]
i don't think secondary_rank is causing the problem. it's optional. you can simply delete obj.iloc[...,:-1,:-1] from the failing line.

**Comment by henrydingliu** [comment]
@jbogaardt do you recall what obj.iloc[...,:-1,:-1] was changed to elsewhere in the package to deal with scalene triangles?

**Review by jbogaardt — APPROVED** [review]

**Comment by jbogaardt** [comment]
> @jbogaardt do you recall what obj.iloc[...,:-1,:-1] was changed to elsewhere in the package to deal with scalene triangles?

I'm not sure, but my instinct is to rely on the logic that produces the valid entries for a scalene triangle's link_ratios:
```python
cl.load_sample('quarterly').link_ratio.nan_triangle
```

**Comment by henrydingliu** [comment]
Thanks @jbogaardt. Found it in the link_ratio code. 

@kennethshsu can you simply delete obj.iloc... from [here](https://github.com/casact/chainladder-python/blob/d21f12523d45441f8b300af2296b00f68b7618fd/chainladder/development/development.py#L139-L142)? That should fix the issue, as secondary_rank is optional. I'll find time this week to add back the right secondary rank.

**Comment by kennethshsu** [comment]
Yap sounds good, thanks Henry, I think that's a good temporary solution for now. 

I added a couple more tests to hopefully catch this. Once `secondary_rank` properly ranks using the underlying triangle, we should be able to pass `test_new_drop_10`.

Do we need another round of code review? I know this request is technically already approved. But @jbogaardt, if it looks good feel free to merge!

**Pull request merged**
