### PR TITLE
497

### PR DESCRIPTION
**Pull request by kennethshsu**
- Fixed a calculation bug in #497 
- Introduced `approximation_grain` in `chainladder.ParallelogramOLF()`
- Added two test cases as discussed in #497

### CODE REVIEW

**Comment by kennethshsu** [comment]
@jbogaardt, are you familiar with these errors? I looked at it in detail and I don't think I understand what is going on...

```python
=========================== short test summary info ============================
ERROR chainladder/methods/tests/test_predict.py - ValueError: Fancy indexing on origin/development is not supported.
ERROR chainladder/workflow/tests/test_predict.py - ValueError: Fancy indexing on origin/development is not supported.
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
```

Is this [line](https://github.com/casact/chainladder-python/blob/6c9ad1c6ae39926f96d9660a18d27959a2a36e1d/chainladder/methods/tests/test_predict.py#L5) causing the error? Why?

**Comment by jbogaardt** [comment]
I'm not sure the specifics on the error from this PR, but the error stems from non-contiguous slices out of origin/development.

Here is a bare-bones example that is not supported by the package where we slice an arbitrary list of origins that are out of sequence:
```python
import chainladder as cl
clrd = cl.load_sample('clrd')
clrd.iloc[:, :, [2, 4, 3]]
```

**Comment by jbogaardt** [comment]
It may be differences in dependencies. Github grabs the latest packages. It is using pandas==2.2.1 .


My suspicion is there are some differences in these versions that is causing it to fail. In issue #494, we have this problem with pandas>2.2.0. I think you just made the same issue visible in our unit tests. I've committed a fix since the pandas team gave a suggestion and also signaled they are unlikely to change the behavior. It seemed to clear those errors, but now has more pointed suggestions for the on-leveling updates.

```shell
FAILED chainladder/utils/tests/test_utilities.py::test_non_vertical_line - assert 0.1746221283369899 < 0.0
FAILED chainladder/utils/tests/test_utilities.py::test_vertical_line - UnboundLocalError: cannot access local variable 'cum_avg_rate_non_leaps' where it is not associated with a value
```

**Comment by jbogaardt** [comment]
they aren't resolved, but they are display so I assumed they were related to package dependencies and not the PR itself. Looking closer, I see you have he following in display.py:
```python
        try:
            self.values
        except:
            print("Triangle is empty")
            return
```
I suspect this is causing it.  Can you let me know your intent with this logic?

**Comment by kennethshsu** [comment]
Ahh, I think that's from another branch to address #491, it's not quite done... I think I messed up my version control while working on the two branches. Let me try to resolve this.

**Pull request merged**
