### PR TITLE
addressed #304, 299, and 305

### PR DESCRIPTION
**Pull request by kennethshsu**

### CODE REVIEW

**Comment by kennethshsu** [comment]
Revised commentary and removed reference to specific Mack papers per #299

**Comment by kennethshsu** [comment]
Also revised the commentary per #305

**Review by jbogaardt — APPROVED** [review]

**Comment by kennethshsu** [comment]
@jbogaardt there's an error `error: numpy 1.22.3 is installed but numpy<1.22,>=1.18 is required by {'numba'}`. Do you know what we need to do to fix this?

**Comment by jbogaardt** [comment]
Seems to be in the [Unit Tests](https://github.com/casact/chainladder-python/blob/master/ci/environment-test.yaml) action but does not afffect the [CI Upstream](https://github.com/casact/chainladder-python/blob/master/ci/environment-latest.yaml) action. It is not clear straight away to me why only one of these environments would cause that They look similar with respect to numpy.  

Given no code changes to the library in this PR, I would recommend merging as is.

**Comment by jbogaardt** [comment]
Interesting, docs failed because of:
```
sphinx.errors.ExtensionError: Could not import extension sphinx_panels (exception: No module named 'sphinx_panels')

Extension error:
Could not import extension sphinx_panels (exception: No module named 'sphinx_panels')
```
This was never explicitly declared in our [docs conda environment](https://github.com/casact/chainladder-python/blob/master/environment-docs.yaml). I'll add it and see if it resolves the docs.

**Comment by jbogaardt** [comment]
Docs still failing because notebooks were executed and committed under the cl_dev environment. This gets hardcoded into the notebook JSON and readthedocs doesn't build that environment. It uses cl_docs, complains that cl_dev doesn't exist and crashes the build.

Trying to figure out how to get readthedocs to override the conda environment embedded in the notebook json. Otherwise, we may need to recommit the notebooks with them using the cl_docs kernel.

**Comment by kennethshsu** [comment]
Hmm, I think I have been doing it using the `cl_dev` environment, but let me submit another PR using the stable kernel.

**Pull request merged**
