### PR TITLE
Implemented fillna() and fixed a bug in astype()

### PR DESCRIPTION
**Pull request by kennethshsu**
```python 
import pandas as pd
import chainladder as cl

cl.__version__
%load_ext lab_black

raa = cl.load_sample("raa")
latest_raa = raa[raa.valuation > "1990-01-01"]

latest_raa.fillna([100, 200, 300, 400, 500])
latest_raa.fillna([100, 200, 300, 400, 500], triangle=False)
latest_raa == latest_raa.fillna(
    [100, 200, 300, 400, 500], triangle=False, inplace=False
)
latest_raa == latest_raa.fillna([100, 200, 300, 400, 500], triangle=False, inplace=True)

latest_raa = raa[raa.valuation > "1990-01-01"]
latest_raa.fillna([100, 200, 300, 400, 500], triangle=True, inplace=False, axis=3)
latest_raa.fillna(
    [100, 200, 300, 400, 500], triangle=True, inplace=False, axis="origin"
)
latest_raa.fillna(
    [100, 200, 300, 400, 500], triangle=True, inplace=False, axis="development"
)
latest_raa.fillna(
    [100, 200, 300, 400, 500], triangle=False, inplace=False, axis=4
)
latest_raa.fillna(50, triangle=True, inplace=False, axis="origin")
latest_raa.fillna(50, triangle=True, inplace=False, axis="origin") == latest_raa.fillna(
    50, triangle=True, inplace=False, axis="development"
```

### CODE REVIEW

**Comment by kennethshsu** [comment]
#260

**Comment by jbogaardt** [comment]
I notice this PR reverts the fix I pushed for #257 five days ago. Was that your intention?

**Comment by kennethshsu** [comment]
No, did I make a mistake on the merge? I didn't see any warnings when I committed.

This is also the first time that I try to develop on a branch and not master, so maybe I messed up...

Can you put that back? I'll do another pull from upstream.

**Comment by jbogaardt** [comment]
Sure.

**Pull request merged**
